kind: pipeline
name: default
steps:
    - name: linter
      image: golang:latest
      environment:
          GOPATH: /usr/local/go/
          GOPROXY: https://mirrors.aliyun.com/goproxy/
      commands:
          - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          - golangci-lint run
    - name: build
      image: golang:latest
      environment:
          GOPROXY: https://mirrors.aliyun.com/goproxy/
      commands:
          - CGO_ENABLED=0 go build -o demo-app
    - name: docker
      image: plugins/docker
      settings:
          repo: drone-fk
          use_cache: true
          username: xiashan
          password: omylove33
          tags:
              - latest
          when:
              event: push
              branch: master
