kind: pipeline
name: default
steps:
    - name: linter
      image: golang:latest
      #environment:
      #    GOPROXY: https://mirrors.aliyun.com/goproxy/
      commands:
          - go get -u github.com/spf13/viper
          - go get -u google.golang.org/grpc
          - go get -u cloud.google.com/go
          - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          - golangci-lint run
    - name: build
      image: golang:latest
      #environment:
      #    GOPROXY: https://mirrors.aliyun.com/goproxy/
      commands:
          - CGO_ENABLED=0 go build -o demo-app
    - name: docker
      image: plugins/docker
      settings:
          registry: 47.52.66.40:82
          repo: 47.52.66.40:82/ssb/drone-fk
          use_cache: true
          username: ss
          password: Aa123456
          auto_tag: true
          insecure: true
          when:
              event: push
              branch: master
